version: '3.7'
services:
  postgresdocker:
    image: postgres:latest
    container_name: tempest_pipeline_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  tempest:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tempest_app
    ports:
      - '3000:8080'
